version: 0.2

phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install node
      - npm install -g npm
      - npm init -y
      - npm i express --save

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run-script build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - aap.js
    - node_modules/**/*
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/**/*
